apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nest
  project: nest-app
  source:
    path: ---------------
    repoURL: https://github.com/yabbal/k8s-nest-deployment.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
