apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest
nameSuffix: -dev
images:
- name: nest-app
  newName: sha-a0c40ea
resources:
- ../../base
patchesStrategicMerge:
- patches/deployment.patch.yml
- patches/service.patch.yml
generatorOptions:
  disableNameSuffixHash: true
