apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest
nameSuffix: -dev
images:
- name: nest-app
  newName: yabbal/k8s-nest-app
  newTag: sha-d201b8a
resources:
- ../../base
patchesStrategicMerge:
- patches/deployment.patch.yml
- patches/service.patch.yml
generatorOptions:
  disableNameSuffixHash: true
