apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest-app
resources:
  - ../../base
patchesStrategicMerge:
  - deployment.yml
images:
  - name: yabbal/k8s-nest-app
    newName: yabbal/k8s-nest-app
    newTag: 0.1.4
