apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest
nameSuffix: -dev
images:
- name: nest-app
  newName: yabbal/k8s-nest-app
  newTag: 05a54a2dd074c52a76ad9f10ae4d64355cee3e79
resources:
- ../../base
patchesStrategicMerge:
- patches/deployment.patch.yml
- patches/service.patch.yml
generatorOptions:
  disableNameSuffixHash: true
