apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest
replicas:
- count: 3
  name: nest-app
images:
- name: nest-app
  newName: 0.3.4
resources:
- ../../base
patchesStrategicMerge:
- patches/hpa.patch.yml
generatorOptions:
  disableNameSuffixHash: true
