apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - application.yml
patches:
  - target:
      kind: Application
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: nest-app-preview
