apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nest-app
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: yabbal
          repo: k8s-nest-app
          labels:
            - preview
        requeueAfterSeconds: 300
  template:
    metadata:
      name: "nest-app-pr-{{number}}"
    spec:
      source:
        repoURL: "https://github.com/yabbal/k8s-nest-deployment.git"
        targetRevision: "main"
        path: overlays/dev
        kustomize:
          nameSuffix: "-pr-{{number}}"
          images:
            - yabbal/k8s-nest-app:{{head_sha}}
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: nest
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
