kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nest-app-dev
  name: nest-app
  namespace: nest
spec:
  selector:
    matchLabels:
      app: nest-app-dev
  template:
    metadata:
      labels:
        app: nest-app-dev
