kind: Deployment
apiVersion: apps/v1
metadata:
  name: nest-app
spec:
  selector:
    matchLabels:
      app: nest-app-dev
  template:
    metadata:
      labels:
        app: nest-app-dev
