apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nest-app
resources:
  - ../../base
patchesStrategicMerge:
  - deployment.patch.yml
  - service.patch.yml
patches:
  - target:
      kind: Deployment
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: nest-app-preview
  - target:
      kind: Service
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: nest-app-service-preview
