apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app-deployment
  namespace: nest-app
  labels:
    app: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: yabbal/k8s-nest-app:latest
          ports:
            - containerPort: 3000
