apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
  namespace: nest
  labels:
    app: nest-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
