apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nest-app
  namespace: nest
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
      type: Resource
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 180
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-app
