apiVersion: v1
kind: Service
metadata:
  labels:
    app: nest-app
  name: nest-app
  namespace: nest
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nest-app
    version: baseline
