name: Configuration check
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Kustomize
        uses: multani/action-setup-kustomize@v1
        with:
          version: 4.5.7

      - name: Check argo conf
        run: kustomize build argocd/overlays/${{ matrix.env }}

      - name: Check conf
        run: kustomize build overlays/${{ matrix.env }}
